config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :goals
    resources :players
    resources :teams
    resources :games

    root to: "goals#index"
  end

  root "home#show"

  resource :home, only: :show
  resources :teams, only: :index
  resources :videos, only: :index

  namespace :api do
    get "/action_type_goals", to: "charts#action_type_goals"
    get "/action_type_goals_against", to: "charts#action_type_goals_against"
    get "/team_goals", to: "charts#team_goals"
    get "/goal_action_type_teams", to: "charts#goal_action_type_teams"
    get "/goal_action_type_match_weeks", to: "charts#goal_action_type_match_weeks"
    get "/teams", to: "teams#index"
    get "/goals/action_types", to: "goals#action_types"
    get "/goals/videos", to: "goals#videos"
    get "/games/match_weeks", to: "games#match_weeks"
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO, Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
  def class_nav_link(link:, color:)
    html_class = "block py-1 md:py-3 pl-1 align-middle no-underline hover:text-gray-900 border-b-2"
    if current_page?(link)
      html_class += " text-#{color}-600 border-#{color}-600 hover:border-#{color}-600"
    else
      html_class += " text-gray-500 border-white hover:border-#{color}-500"
    end

    html_class
  end

  def class_nav_link_text(link:, color:)
    if current_page?(link)
      "fas fa-home fa-fw mr-3 text-#{color}-600"
    else
      "fas fa-home fa-fw mr-3"
    end
  end
end

app/views/application/_header.html.erb
<nav id="header" class="bg-white fixed w-full z-10 top-0 shadow">
  <div class="w-full container mx-auto flex flex-wrap items-center mt-0 pt-3 pb-3 md:pb-0">

    <div class="w-1/2 pl-2 md:pl-0">
      <a class="text-gray-900 text-base xl:text-xl no-underline hover:no-underline font-bold" href="#">
        <i class="fas fa-sun text-orange-600 pr-3"></i> Futsal D1
      </a>
    </div>
    <div class="w-1/2 pr-0">
      <div class="flex relative inline-block float-right">
        <div class="relative text-sm">
          <button id="userButton" class="flex items-center focus:outline-none mr-3">
            <img class="w-8 h-8 rounded-full mr-4" src="http://i.pravatar.cc/300" alt="Avatar of User"> <span class="hidden md:inline-block">Hi, User </span>
          </button>
        </div>

        <div class="block lg:hidden pr-4">
          <button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-gray-900 hover:border-teal-500 appearance-none focus:outline-none">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <title>Menu</title>
              <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
            </svg>
          </button>
        </div>
      </div>
    </div>

    <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block mt-2 lg:mt-0 bg-white z-20" id="nav-content">
      <ul class="list-reset lg:flex flex-1 items-center px-4 md:px-0">
        <li class="mr-6 my-2 md:my-0">
          <%= link_to root_path,
            class: class_nav_link(link: root_path, color: "orange") do %>
              <i class=<%= class_nav_link_text(link: root_path, color: "orange") %>></i>
              <span class="pb-1 md:pb-0 text-sm">Home</span>
          <% end %>
        </li>
        <li class="mr-6 my-2 md:my-0">
          <%= link_to videos_path,
            class: class_nav_link(link: videos_path, color: "pink") do %>
              <i class=<%= class_nav_link_text(link: videos_path, color: "pink") %>></i>
              <span class="pb-1 md:pb-0 text-sm">Videos</span>
          <% end %>
        </li>
        <li class="mr-6 my-2 md:my-0">
          <%= link_to "#",
            class: class_nav_link(link: "#", color: "purple") do %>
              <i class=<%= class_nav_link_text(link: "#", color: "purple") %>></i>
              <span class="pb-1 md:pb-0 text-sm">Fake</span>
          <% end %>
        </li>
        <li class="mr-6 my-2 md:my-0">
          <%= link_to "#",
            class: class_nav_link(link: "#", color: "green") do %>
              <i class=<%= class_nav_link_text(link: "#", color: "green") %>></i>
              <span class="pb-1 md:pb-0 text-sm">Fake</span>
          <% end %>
        </li>
        <li class="mr-6 my-2 md:my-0">
          <%= link_to "#",
            class: class_nav_link(link: "#", color: "red") do %>
              <i class=<%= class_nav_link_text(link: "#", color: "red") %>></i>
              <span class="pb-1 md:pb-0 text-sm">Fake</span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/application/_javascript.html.erb
<%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

<%= yield :javascript %>